name: Build Ketamine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Build with xcodebuild
      run: |
        xcodebuild build \
          -project Ketamine.xcodeproj \
          -scheme Ketamine \
          -sdk iphonesimulator \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
